using System;
namespace SpartanUserManagement
{
    public class SqlQueries
    {
        public static String GetUserById_Sql = @"SELECT	Id,
                                                        AppName,
                                                        UserName,
                                                        Type,
                                                        Company,
                                                        FirstName,
                                                        MiddleName,
                                                        LastName,
                                                        Gender,
                                                        MaritalStatus,
                                                        Email,
                                                        EmailSignature,
                                                        EmailProvider,
                                                        JobTitle,
                                                        BusinessPhone,
                                                        HomePhone,
                                                        MobilePhone,
                                                        FaxNumber,
                                                        Address,
                                                        Address1,
                                                        City,
                                                        State,
                                                        Province,
                                                        ZipCode,
										                Country,
										                WebPage,
										                Avatar,
										                About,
										                DoB,
										                IsActive,
										                ReportsToId
								                FROM	Users
								                WHERE	Id = @Id;";


        public static String GetUserByUserName_Sql = @"SELECT	Id,
                                                        AppName,
                                                        UserName,
                                                        Type,
                                                        Company,
                                                        FirstName,
                                                        MiddleName,
                                                        LastName,
                                                        Gender,
                                                        MaritalStatus,
                                                        Email,
                                                        EmailSignature,
                                                        EmailProvider,
                                                        JobTitle,
                                                        BusinessPhone,
                                                        HomePhone,
                                                        MobilePhone,
                                                        FaxNumber,
                                                        Address,
                                                        Address1,
                                                        City,
                                                        State,
                                                        Province,
                                                        ZipCode,
										                Country,
										                WebPage,
										                Avatar,
										                About,
										                DoB,
										                IsActive,
										                ReportsToId
								                FROM	Users
								                WHERE	UserName = @Username;";

        public static String GetUserByEmail_Sql = @"SELECT	Id,
                                                        AppName,
                                                        UserName,
                                                        Type,
                                                        Company,
                                                        FirstName,
                                                        MiddleName,
                                                        LastName,
                                                        Gender,
                                                        MaritalStatus,
                                                        Email,
                                                        EmailSignature,
                                                        EmailProvider,
                                                        JobTitle,
                                                        BusinessPhone,
                                                        HomePhone,
                                                        MobilePhone,
                                                        FaxNumber,
                                                        Address,
                                                        Address1,
                                                        City,
                                                        State,
                                                        Province,
                                                        ZipCode,
										                Country,
										                WebPage,
										                Avatar,
										                About,
										                DoB,
										                IsActive,
										                ReportsToId
								                FROM	Users
								                WHERE	Email = @email;";

        public static String GetAllUsers_Sql = @"SELECT	Id,
										                AppName,
										                UserName,
										                Type,
										                Company,
										                FirstName,
										                MiddleName,
										                LastName,
										                Gender,
										                MaritalStatus,
										                Email,
										                EmailSignature,
										                EmailProvider,
										                JobTitle,
										                BusinessPhone,
										                HomePhone,
										                MobilePhone,
										                FaxNumber,
										                Address,
										                Address1,
										                City,
										                State,
										                Province,
										                ZipCode,
										                Country,
										                WebPage,
										                Avatar,
										                About,
										                DoB,
										                IsActive
								                FROM	Users;";


        //Only for Development and UnitTesting
        public static string DeleteAllUsers_Sql = @"DELETE FROM USERS";

        public static String AddUser_Sql = @"INSERT INTO [Users]
								                    (
								                    	Id,
								                    	AppName,
								                    	UserName,
								                    	PasswordHash,
								                    	Type,
								                    	Company,
								                    	FirstName,
								                    	MiddleName,
								                    	LastName,
								                    	Gender,
								                    	MaritalStatus,
								                    	Email,
								                    	EmailSignature,
								                    	EmailProvider,
								                    	JobTitle,
								                    	BusinessPhone,
								                    	HomePhone,
								                    	MobilePhone,
								                    	FaxNumber,
								                    	Address,
								                    	Address1,
								                    	City,
								                    	State,
								                    	Province,
								                    	ZipCode,
								                    	Country,
								                    	WebPage,
								                    	Avatar,
								                    	About,
								                    	DoB,
								                    	IsActive,
								                    	AccessFailedCount,
								                    	LockEnabled,
								                    	LockoutDescription,
								                    	ReportsToId,
								                    	DateCreated,
								                    	LastUpdated
								                    )
								                    VALUES
								                    (
								                    	@Id,
								                    	@AppName,
								                    	@UserName,
								                    	@PasswordHash,
								                    	@Type,
								                    	@Company,
								                    	@FirstName,
								                    	@MiddleName,
								                    	@LastName,
								                    	@Gender,
								                    	@MaritalStatus,
								                    	@Email,
								                    	@EmailSignature,
								                    	@EmailProvider,
								                    	@JobTitle,
								                    	@BusinessPhone,
								                    	@HomePhone,
								                    	@MobilePhone,
								                    	@FaxNumber,
								                    	@Address,
								                    	@Address1,
								                    	@City,
								                    	@State,
								                    	@Province,
								                    	@ZipCode,
								                    	@Country,
								                    	@WebPage,
								                    	@Avatar,
								                    	@About,
								                    	@DoB,
								                    	@IsActive,
								                    	@AccessFailedCount,
								                    	@LockEnabled,
								                    	@LockoutDescription,
								                    	@ReportsToId,
								                    	@DateCreated,
								                    	@LastUpdated
								                    );";

    }
}
