using System;
namespace SpartanUserManagement
{
    public class SqlQueries
    {
        public static String GetUserById_Sql = @"SELECT	Id,
                                                        AppName,
                                                        UserName,
                                                        Type,
                                                        Company,
                                                        FirstName,
                                                        MiddleName,
                                                        LastName,
                                                        Gender,
                                                        MaritalStatus,
                                                        Email,
                                                        EmailSignature,
                                                        EmailProvider,
                                                        JobTitle,
                                                        BusinessPhone,
                                                        HomePhone,
                                                        MobilePhone,
                                                        FaxNumber,
                                                        Address,
                                                        Address1,
                                                        City,
                                                        State,
                                                        Province,
                                                        ZipCode,
														Country,
														WebPage,
														Avatar,
														About,
														DoB,
														IsActive,
								                    	AccessFailedCount,
								                    	LockEnabled,
								                    	LockoutDescription,
								                    	ReportsToId,
								                    	DateCreated,
								                    	LastUpdated
												FROM	Users
												WHERE	Id = @Id;";

        public static String GetUserByUserName_Sql = @"SELECT	Id,
                                                        AppName,
                                                        UserName,
                                                        Type,
                                                        Company,
                                                        FirstName,
                                                        MiddleName,
                                                        LastName,
                                                        Gender,
                                                        MaritalStatus,
                                                        Email,
                                                        EmailSignature,
                                                        EmailProvider,
                                                        JobTitle,
                                                        BusinessPhone,
                                                        HomePhone,
                                                        MobilePhone,
                                                        FaxNumber,
                                                        Address,
                                                        Address1,
                                                        City,
                                                        State,
                                                        Province,
                                                        ZipCode,
														Country,
														WebPage,
														Avatar,
														About,
														DoB,
														IsActive,
								                    	AccessFailedCount,
								                    	LockEnabled,
								                    	LockoutDescription,
								                    	ReportsToId,
								                    	DateCreated,
								                    	LastUpdated
												FROM	Users
												WHERE	UserName = @Username;";

        public static String GetUserByEmail_Sql = @"SELECT	Id,
                                                        AppName,
                                                        UserName,
                                                        Type,
                                                        Company,
                                                        FirstName,
                                                        MiddleName,
                                                        LastName,
                                                        Gender,
                                                        MaritalStatus,
                                                        Email,
                                                        EmailSignature,
                                                        EmailProvider,
                                                        JobTitle,
                                                        BusinessPhone,
                                                        HomePhone,
                                                        MobilePhone,
                                                        FaxNumber,
                                                        Address,
                                                        Address1,
                                                        City,
                                                        State,
                                                        Province,
                                                        ZipCode,
														Country,
														WebPage,
														Avatar,
														About,
														DoB,
														IsActive,
								                    	AccessFailedCount,
								                    	LockEnabled,
								                    	LockoutDescription,
								                    	ReportsToId,
								                    	DateCreated,
								                    	LastUpdated
												FROM	Users
												WHERE	Email = @email;";

        public static String GetActiveUsers_Sql = @"SELECT	Id,
										                AppName,
										                UserName,
										                Type,
										                Company,
										                FirstName,
										                MiddleName,
										                LastName,
										                Gender,
										                MaritalStatus,
										                Email,
										                EmailSignature,
										                EmailProvider,
										                JobTitle,
										                BusinessPhone,
										                HomePhone,
										                MobilePhone,
										                FaxNumber,
										                Address,
										                Address1,
										                City,
										                State,
										                Province,
										                ZipCode,
										                Country,
										                WebPage,
										                Avatar,
										                About,
										                DoB,
										                IsActive,
								                    	AccessFailedCount,
								                    	LockEnabled,
								                    	LockoutDescription,
								                    	ReportsToId,
								                    	DateCreated,
								                    	LastUpdated
								                FROM	Users
                                                WHERE   IsActive = 1
                                                AND     LockEnabled = 0";

        //Only for Development and UnitTesting
        public static String DeleteAllUsers_Sql = @"DELETE FROM USERS";

        //Use this to Delete or Restore an Account
        public static String DisableUser_Sql = @"UPDATE	Users
												SET	    IsActive = 0,
														LastUpdated = GETDATE()
												WHERE	Id = @Id;";

    
    public static String AddUser_Sql = @"INSERT INTO Users
								                    (
								                    	Id,
								                    	AppName,
								                    	UserName,
								                    	PasswordHash,
								                    	Type,
								                    	Company,
								                    	FirstName,
								                    	MiddleName,
								                    	LastName,
								                    	Gender,
								                    	MaritalStatus,
								                    	Email,
								                    	EmailSignature,
								                    	EmailProvider,
								                    	JobTitle,
								                    	BusinessPhone,
								                    	HomePhone,
								                    	MobilePhone,
								                    	FaxNumber,
								                    	Address,
								                    	Address1,
								                    	City,
								                    	State,
								                    	Province,
								                    	ZipCode,
								                    	Country,
								                    	WebPage,
								                    	Avatar,
								                    	About,
								                    	DoB,
								                    	IsActive,
								                    	AccessFailedCount,
								                    	LockEnabled,
								                    	LockoutDescription,
								                    	ReportsToId,
								                    	DateCreated,
								                    	LastUpdated
								                    )
								                    VALUES
								                    (
								                    	@Id,
								                    	@AppName,
								                    	@UserName,
								                    	@PasswordHash,
								                    	@Type,
								                    	@Company,
								                    	@FirstName,
								                    	@MiddleName,
								                    	@LastName,
								                    	@Gender,
								                    	@MaritalStatus,
								                    	@Email,
								                    	@EmailSignature,
								                    	@EmailProvider,
								                    	@JobTitle,
								                    	@BusinessPhone,
								                    	@HomePhone,
								                    	@MobilePhone,
								                    	@FaxNumber,
								                    	@Address,
								                    	@Address1,
								                    	@City,
								                    	@State,
								                    	@Province,
								                    	@ZipCode,
								                    	@Country,
								                    	@WebPage,
								                    	@Avatar,
								                    	@About,
								                    	@DoB,
								                    	@IsActive,
								                    	@AccessFailedCount,
								                    	@LockEnabled,
								                    	@LockoutDescription,
								                    	@ReportsToId,
								                    	@DateCreated,
								                    	@LastUpdated
								                    );";

        public static String UpdateUser_Sql = @"UPDATE	Users
												SET	AppName = @AppName,
														UserName = @UserName,
														PasswordHash = @PasswordHash,
														Type = @Type,
														Company = @Company,
														FirstName = @FirstName,
														MiddleName = @MiddleName,
														LastName = @LastName,
														Gender = @Gender,
														MaritalStatus = @MaritalStatus,
														Email = @Email,
														EmailSignature = @EmailSignature,
														EmailProvider = @EmailProvider,
														JobTitle = @JobTitle,
														BusinessPhone = @BusinessPhone,
														HomePhone = @HomePhone,
														MobilePhone = @MobilePhone,
														FaxNumber = @FaxNumber,
														Address = @Address,
														Address1 = @Address1,
														City = @City,
														State = @State,
														Province = @Province,
														ZipCode = @ZipCode,
														Country = @Country,
														WebPage = @WebPage,
														Avatar = @Avatar,
														About = @About,
														DoB = @DoB,
														IsActive = @IsActive,
														AccessFailedCount = @AccessFailedCount,
														LockEnabled = @LockEnabled,
														LockoutDescription = @LockoutDescription,
														ReportsToId = @ReportsToId,
														DateCreated = @DateCreated,
														LastUpdated = @LastUpdated
												WHERE	Id = @Id;";

    }

}